QuanLyPhongMay_LichTH/Controllers/StartUpController.cs
using QuanLyPhongMay_LichTH.Common;
using QuanLyPhongMay_LichTH.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace QuanLyPhongMay_LichTH.Controllers
{
    public class StartUpController : Controller
    {
        // GET: StartUp
        public ActionResult Login_StartUp(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.UserName, model.Password/*model.Password*/);
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLoginSec();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.Id;
                    userSession.GroupID = user.GroupID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    // List quyền của ng dùng
                    List<string> privilegeLevelsNew = dao.GetListCredential(user.UserName.Trim());
                    Session.Add(CommonConstants.SESSION_CREDENTIALS, privilegeLevelsNew);
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else if (result == -3)
                {
                    ModelState.AddModelError("", "Tài khoản của bạn không có quyền truy cập ");
                }
                else
                {
                    ModelState.AddModelError("", "đăng nhập không đúng.");
                }
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

QuanLyPhongMay_LichTH/Views/StartUp/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

QuanLyPhongMay_LichTH/Views/StartUp/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

QuanLyPhongMay_LichTH/Views/StartUp/Login_StartUp.cshtml
@model QuanLyPhongMay_LichTH.Models.LoginModel
@{
    ViewBag.Title = "Quản Lý Phòng Máy";
}
<link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/css/bootstrap-reset.css" rel="stylesheet" />
<!--external css-->
<link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<!-- Custom styles for this template -->
<link href="~/Content/css/style.css" rel="stylesheet" />
<link href="~/Content/css/style-responsive.css" rel="stylesheet" />
<link href="~/Content/css/mytcsss.css" rel="stylesheet" />
<style>
    .control-label {
        font-weight: bold !important;
    }

    .form-control {
        color: black !important;
        padding: 6px !important;
        margin-bottom: 5px !important;
        font-size: 15px !important;
    }

    .btn-login {
        box-shadow: 0 4px #afd3e0 !important;
        background-color: #56abd4 !important;
    }

    .form-signin {
        height: 330px !important;
    }
</style>
<body class="login-body">
    <div class="container">
        @using (Html.BeginForm("Login_StartUp", "StartUp", FormMethod.Post, new { @class = "form-horizontal form-signin", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <h2 class="form-signin-heading">Đăng Nhập hệ thống</h2>
            <div class="login-wrap">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group center">
                    @Html.LabelFor(model => model.UserName, "Tên Người Dùng ", new { @class = "col-md-4 control-label" })
                    <div class="col-md-8">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, "Mật Khẩu", new { @class = "col-md-4 control-label" })
                    <div class="col-md-8">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-10">
                        @*<div class="checkbox">
                                @Html.CheckBoxFor(m => m.RememberMe)
                                @Html.LabelFor(m => m.RememberMe)
                            </div>*@
                    </div>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">Đăng Nhập</button>
            </div>

        }
    </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}